# Generated by Django 4.2 on 2024-01-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='type',
            field=models.CharField(choices=[('Other', 'Other'), ('Academy', 'Academy'), ('Office', 'Office'), ('Home', 'Home')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='type',
            field=models.CharField(choices=[('Other', 'Other'), ('Academy', 'Academy'), ('Office', 'Office'), ('Home', 'Home')], max_length=10),
        ),
    ]
