# Generated by Django 4.2 on 2024-03-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraddress_type_alter_userphonenumber_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Academy', 'Academy'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Academy', 'Academy'), ('Other', 'Other')], max_length=10),
        ),
    ]
